name: Deploy to GitHub pages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          # submodules: true # Fetch quartz (true OR recursive)
          fetch-depth: 0 # Fetch all history
      - name: Shallow clone submodules
        run: git submodule update --init --recursive --depth=1
      - name: Cache plugins
        id: cache-plugins
        uses: actions/cache@v6
        with:
          path: './runtime/.quartz/plugins'
          key: ${{ runner.os }}-quartz-plugins-${{ hashFiles('quartz.config.yaml') }}
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v6
      - name: Strip Protocol from URL
        id: clean_url
        run: |
          # Get the raw URL (e.g., https://github.io)
          RAW_URL="${{ steps.pages.outputs.base_url }}"

          # Strip both http:// and https:// prefixes
          CLEANED_URL="${RAW_URL#http:///}"
          CLEANED_URL="${CLEANED_URL#https://}"

          # Save it to the environment output
          echo "stripped_url=$CLEANED_URL" >> $GITHUB_OUTPUT
      - name: Copy documents and settings to runtime
        run: |
          yq -i '.configuration.baseUrl = "${{ steps.clean_url.outputs.stripped_url }}"' quartz.config.yaml
          cp -vr quartz.config.yaml content/ runtime/
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: 'runtime/.node-version'
          cache-dependency-path: 'runtime/package-lock.json'
          cache: 'npm'
      - name: Build website
        run: 	cd runtime && npm ci && npx quartz plugin install --from-config && npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: runtime/public/

  # Deployment job
  deploy:
    needs: build
    if: ${{ github.ref == 'refs/heads/main'}}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
      actions: read     # to download an artifact uploaded by `actions/upload-pages-artifact@v3`
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-slim
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
